# Generated by Django 3.1.4 on 2020-12-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='业务名称')),
                ('use', models.CharField(blank=True, max_length=50, verbose_name='用途')),
                ('network', models.CharField(blank=True, choices=[('gongan', '公安网'), ('internet', '互联网')], default='gongan', max_length=20, verbose_name='所属网络')),
                ('login_url', models.CharField(blank=True, max_length=50, verbose_name='登录方式')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='密码')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '业务',
                'verbose_name_plural': '业务',
            },
        ),
    ]
