# Generated by Django 3.1.4 on 2020-12-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20201217_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhost',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='host',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/hosts/%Y/%m', verbose_name='附件'),
        ),
    ]
