# Generated by Django 3.1.4 on 2020-12-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20201217_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhost',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=20, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='historicalhost',
            name='manager_ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='管理IP'),
        ),
        migrations.AddField(
            model_name='historicalhost',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='historicalhost',
            name='username',
            field=models.CharField(blank=True, max_length=20, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='host',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=20, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='host',
            name='manager_ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='管理IP'),
        ),
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='host',
            name='username',
            field=models.CharField(blank=True, max_length=20, verbose_name='用户'),
        ),
    ]
