# Generated by Django 3.1.4 on 2020-12-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20201217_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhost',
            name='disk_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='硬盘个数'),
        ),
        migrations.AlterField(
            model_name='historicalhost',
            name='disk_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='硬盘大小'),
        ),
        migrations.AlterField(
            model_name='historicalhost',
            name='memory_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存卡条数'),
        ),
        migrations.AlterField(
            model_name='historicalhost',
            name='memory_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存大小'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='硬盘个数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='硬盘大小'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存卡条数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存大小'),
        ),
    ]
