# Generated by Django 3.1.4 on 2020-12-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20201217_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhost',
            name='cpu_core',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU核数'),
        ),
        migrations.AlterField(
            model_name='historicalhost',
            name='cpu_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU颗数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_core',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU核数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU颗数'),
        ),
    ]
