# Generated by Django 3.1.4 on 2020-12-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20201217_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhost',
            name='ip',
            field=models.CharField(db_index=True, max_length=20, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=20, unique=True, verbose_name='IP'),
        ),
    ]
