# Generated by Django 3.1.4 on 2020-12-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20201217_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/hosts/%Y-%m-%d', verbose_name='附件'),
        ),
    ]
