# Generated by Django 3.1.4 on 2020-12-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_auto_20201217_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhost',
            name='device_type',
            field=models.CharField(blank=True, choices=[('virtual', '虚拟机'), ('physical', '物理机'), ('other', '其他')], default='', max_length=20, null=True, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='historicalhost',
            name='network_type',
            field=models.CharField(blank=True, choices=[('gongan', '公安网'), ('internet', '互联网'), ('shipin', '视频专网')], default='', max_length=20, null=True, verbose_name='网络类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='device_type',
            field=models.CharField(blank=True, choices=[('virtual', '虚拟机'), ('physical', '物理机'), ('other', '其他')], default='', max_length=20, null=True, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='network_type',
            field=models.CharField(blank=True, choices=[('gongan', '公安网'), ('internet', '互联网'), ('shipin', '视频专网')], default='', max_length=20, null=True, verbose_name='网络类型'),
        ),
    ]
