# Generated by Django 3.1.4 on 2020-12-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20201217_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhost',
            name='offline_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='下架日期'),
        ),
        migrations.AlterField(
            model_name='historicalhost',
            name='online_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='上架日期'),
        ),
        migrations.AlterField(
            model_name='historicalhost',
            name='status',
            field=models.CharField(blank=True, choices=[('using', '使用中'), ('stopping', '已停用'), ('repairing', '维修中'), ('reserve', '备用'), ('dumping', '报废')], default='using', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='host',
            name='offline_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='下架日期'),
        ),
        migrations.AlterField(
            model_name='host',
            name='online_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='上架日期'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, choices=[('using', '使用中'), ('stopping', '已停用'), ('repairing', '维修中'), ('reserve', '备用'), ('dumping', '报废')], default='using', max_length=10, verbose_name='状态'),
        ),
    ]
