# Generated by Django 3.1.4 on 2021-02-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_auto_20201218_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhost',
            name='warranty_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='维保截止日期'),
        ),
        migrations.AlterField(
            model_name='host',
            name='warranty_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='维保截止日期'),
        ),
    ]
